### ISSUE TITLE
Tooltip content being cutoff when tooltips extends outside the container that holds it

### ISSUE THREAD

**Issue by BennyBaruba** [Esri/calcite-web#1086]
I have a location in the app that we are building where the calcite web tooltip is cutting off the text inside it, when the tooltip extends beyond the container that holds it:
![Screen Shot 2019-05-21 at 11 59 30 AM](https://user-images.githubusercontent.com/5122225/58113483-96c76580-7bc3-11e9-8da6-c35d1d0101fc.png)

It appears that the same issue is happening in the examples in the online doc for calcite web:
![Screen Shot 2019-05-21 at 12 01 12 PM](https://user-images.githubusercontent.com/5122225/58113534-b6f72480-7bc3-11e9-9583-631def45c20f.png)

Ideally it would nice to either have the option for the tooltip to sit on top, so it can extend beyond the boundary of the containing holding it.  Or another option would be to have the ability for the tooltip and content inside of it, to adjust to fit within the containing holding it.

**Comment by paulcpederson** [comment]
The only way to do this would be to create a element at the document root that's dynamically positioned with JavaScript. So it would be a breaking change and fairly heavy-handed.

As a work around, I usually just position the tooltip with a directional class that will fit inside the container. I also have a couple additional classes like `tooltip-bottom-right` and `tooltip-bottom-left` that will put the tooltip below but flush left or right instead of centered:

```css
.tooltip-bottom-right:before {
  right: 9px;
}

html[dir="rtl"] .tooltip-bottom-right:before {
  right: auto;
  left: 9px;
}

.tooltip-bottom-left:after, .tooltip-bottom-right:after {
  top: 100%;
  margin-top: 5px;
  line-height: 1.5;
  -webkit-transform: translateX(0%);
  -moz-transform: translateX(0%);
  -ms-transform: translateX(0%);
  -o-transform: translateX(0%);
  transform: translateX(0%);
}

.tooltip-bottom-left:after {
  max-width: 170px;
}

.tooltip-bottom-left:after, html[dir="rtl"] .tooltip-bottom-right:after {
  right: auto;
  left: -9px;
}

.tooltip-bottom-right:after, html[dir="rtl"] .tooltip-bottom-left:after {
  right: -9px;
  left: auto;
}
```

We can try to address this use case in the 2.0 branch (next version).
