### ISSUE TITLE
Padding is weird for nested lists

### ISSUE THREAD

**Issue by patrickarlt** [Esri/calcite-web#388]
Nested lists are a little odd:

![implementing_application_authentication___arcgis_for_developers](https://cloud.githubusercontent.com/assets/378557/10271281/b23b20ae-6abf-11e5-8084-30d0a2fca44d.png)

Notice the extra padding where the nested list ends.

I think we need something like this:

``` css
// lists inside list items
li ul, li, ol {
  margin-bottom: 0;
}
```
