### ISSUE TITLE
error in _columns.scss

### ISSUE THREAD

**Issue by bradleywertman** [Esri/calcite-web#395]
Looks like the if statement didn't make it into the set of parenthesis above. https://github.com/Esri/calcite-web/blob/v0.14.0/lib/sass/calcite-web/grid/_columns.scss#L221

matching previous patterns above, should the fix be?

``` scss
      .#{$prefix}#{$small-class}-last-column {
        margin-right: -($column-gutter / 2);
        @if ($include-right-to-left) {
            html[dir="rtl"] & {
              margin-right: 0;
              margin-left: -$column-gutter / 2;
            }
        }
      }
```

Otherwise...
![image](https://cloud.githubusercontent.com/assets/3075887/10324305/7a2630a8-6c3d-11e5-9e8a-f7d0059d2104.png)

looks to have been introduced at 55818f65f2970e1b9291a31d24a16ee136de8ccb
