### ISSUE TITLE
Hide p:empty

### ISSUE THREAD

**Issue by patrickarlt** [Esri/calcite-web#446]
``` css
p:empty {
  display: none;
}
```

or

``` css
p:empty {
  margin: 0;
}
```

Trisoft generates empty `<p>` tags all the time which is messing up spacing in issues in https://github.com/ArcGIS/arcgis-for-developers/issues/3145
