### ISSUE TITLE
Table - modifier please

### ISSUE THREAD

**Issue by odoe** [Esri/calcite-web#683]
Right now Calcite-Web automatically styles tables.

This unfortunately breaks some widgets in the ArcGIS API for JavaScript like the Legend widget in 3.x.

![screen shot 2016-10-05 at 1 42 58 pm](https://cloud.githubusercontent.com/assets/206462/19130847/dfbfd570-8b01-11e6-9027-cc6736b317f2.png)

Without Calcite-Web in my page, it looks like this.

![screen shot 2016-10-05 at 1 47 08 pm](https://cloud.githubusercontent.com/assets/206462/19130937/42f2fafa-8b02-11e6-9030-560a64e4c310.png)

I would need to override these styles to fix this in my application.

Thanks!

**Comment by paulcpederson** [comment]
@odoe I feel for you on this one. Overriding all of these table styles was a massive pain in Online.

Maybe dumb question: if we didn't style tables, wouldn't you still have to override the browser's default table styles though? Browsers add padding and borders to tables by default, don't they? So you'd still have to have a reset, right?

To clarify, are you looking for a modifier which removes all of the table styles, or are you looking for a modifier which selectively adds table styles to only certain tables?

**Comment by odoe** [comment]
My first inclination is a modifier to add the tables styles, something simple like `.table`. But the idea of a modifier to remove them is interesting. If I could add something like `.table-clear` to the container of a table, like the Legend widget, that could work out pretty well without me having to style all my tables that I would like to _Calcitified_.

**Comment by paulcpederson** [comment]
@nikolaswise what are your thoughts on this?

**Comment by nikolaswise** [comment]
I would prefer to move in the direction of a modifier to clear — `.table-no-thank-you`

Tables and forms are two things where I feel styling the default elements provide a lot of added value: in terms of basic html just looking good, and support for markdown documents, things like that.

@odoe could you provide a sample of how we could set tables so they get out of your way as much as possible?

**Comment by odoe** [comment]
In order to get the Legend in 3.x to look correct, I had to do the following. I'm sure there's a better way to do it though.

Some of the padding and font related properties were ok and still have my Legend widget looking ok.

```css
table {
  width: auto;
  background-color: rgba(0,0,0,0);
  border-collapse: auto;
  border-spacing: 0;
  border: 0 solid #ccc;
  text-align: left;
  overflow: auto;
  font-size: 0.875rem;
  line-height: 1.55rem;
  margin-bottom: 0;
}

table > tbody {
  overflow: auto;
  width: 100%;
}

table th, table td {
    font-weight: 300;
    border-left: 0 solid #ccc;
    border-right: 0 solid #ccc;
    padding: 0.51667rem;
}

table tr {
  border-bottom: 0 solid #ccc;
  text-align: left;
}
```

![screen shot 2016-10-05 at 3 53 05 pm](https://cloud.githubusercontent.com/assets/206462/19134615/dd9e7a96-8b13-11e6-99d6-7ec9a904f237.png)

Thanks!
