### ISSUE TITLE
Missing '.dropdown-right' RTL support

### ISSUE THREAD

**Issue by nullrocks** [Esri/calcite-web#770]
### Fix?
```scss
html[dir=rtl] {
  .dropdown-menu.dropdown-right{
    left: 0;
    right: initial;
  }
}
```
