### ISSUE TITLE
Automatically wrap long <code> blocks in scrollbar

### ISSUE THREAD

**Issue by patrickarlt** [Esri/calcite-web#888]
We ran into a bunch of issues on the developers site were users had created pages with REALLY long strings like URLs wrapped inside `<code>` blocks that were breaking out of their containers. Since there are dozens off these scattered across docs with different authors I took it upon myself to find a universal CSS based solution.

Basically `<code>` elements will grow until they reach the width of their containers, then they will start to scroll x. You can see this live in https://jsbin.com/duwivol/edit?html,css,output. This gives the appearance of `pre > code` but without any HTML updates. Short `<code>` elements behave as normal.

```css
code.fix {
  overflow: auto; /** show a scrollbar automatically**/
  display: inline-block; /**  display as a block **/
  white-space: nowrap; /** do not wrap text at all **/
  box-sizing: border-box;
  max-width: 100%; /** fallback width for non -calc browser **/
  box-shadow: 1px 0 0px #efefef, 0px 1px 0px #efefef, -1px 0 0px #efefef, 0px -1px 0px #efefef; /** Fake a border around the scrollbar **/
  border-radius: 0;  /** remove border radius to clear scrollbar **/
  vertical-align: -50%;
  border: none;
}
```

![output jsbin com_duwivol](https://user-images.githubusercontent.com/378557/37356152-959edf48-26a2-11e8-81ff-76bebf2ce363.png)
